version: '2.1'

services:
  master:
    build:
      context: .
      dockerfile: master/Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    volumes:
      - ./runtime/runs:/usr/src/app/runs
      - ./runtime/tests:/usr/src/app/tests
      - ./runtime/submissions:/usr/src/app/submissions
      - ./runtime/tasks:/usr/src/app/tasks
  slave:
    build:
      context: .
      dockerfile: slave/Dockerfile
    privileged: true
    volumes:
      - ./runtime/runs:/usr/src/app/runs
      - ./runtime/tests:/usr/src/app/tests
      - ./runtime/submissions:/usr/src/app/submissions
      - ./runtime/tasks:/usr/src/app/tasks
