version: '2.1'

services:
  master:
    build:
      context: .
      dockerfile: master/Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    volumes:
      - ./runtime/runs:/usr/src/app/runs
      - ./runtime/tests:/usr/src/app/tests
      - ./runtime/solutions:/usr/src/app/solutions
      - ./runtime/tasks:/usr/src/app/tasks
  slave:
    image: nsjail
    build:
      context: .
      dockerfile: slave/Dockerfile
    privileged: true
    volumes:
      - ./runtime/runs:/arch/slave/runs
      - ./runtime/tests:/arch/slave/tests
      - ./runtime/solutions:/arch/slave/solutions
      - ./runtime/tasks:/arch/slave/tasks
